// Code generated by protoc-gen-mcp-gateway. DO NOT EDIT.
// source: echo.proto

package main

import (
	"context"
	"fmt"

	"github.com/linkbreakers-com/grpc-mcp-gateway/runtime"
	"google.golang.org/protobuf/types/known/structpb"
)

// RegisterEchoServiceMCPHandler registers stateless MCP tools for EchoService.
func RegisterEchoServiceMCPHandler(mux *runtime.MCPServeMux, client EchoServiceClient) {
	if mux == nil {
		panic("mcp mux is nil")
	}
	if client == nil {
		panic("grpc client is nil")
	}

	mux.RegisterTool(&runtime.ToolHandler{
		Name:        "echo",
		Title:       "Echo",
		Description: "Echoes structured input back to the caller.",
		InputSchema: map[string]any{
			"additionalProperties": true,
			"type":                 "object",
		},
		ReadOnly: true,
		Handler: func(ctx context.Context, args map[string]any) (any, error) {
			req := &structpb.Struct{}
			if err := runtime.DecodeArgs(args, req); err != nil {
				return nil, fmt.Errorf("invalid arguments: %v", err)
			}
			resp, err := client.Echo(ctx, req)
			if err != nil {
				return nil, err
			}
			return runtime.EncodeProto(resp)
		},
	})
}
