// Code generated by protoc-gen-mcp-gateway. DO NOT EDIT.
// source: greeter.proto

package greeter

import (
	"context"
	"fmt"

	"github.com/linkbreakers-com/grpc-mcp-gateway/runtime"
)

// RegisterGreeterMCPHandler registers stateless MCP tools for Greeter.
func RegisterGreeterMCPHandler(mux *runtime.MCPServeMux, client GreeterClient) {
	if mux == nil {
		panic("mcp mux is nil")
	}
	if client == nil {
		panic("grpc client is nil")
	}

	mux.RegisterTool(&runtime.ToolHandler{
		Name:        "greeter.say_hello",
		Title:       "Say Hello",
		Description: "Greets a caller by name.",
		InputSchema: map[string]any{
			"additionalProperties": false,
			"properties": map[string]any{
				"name": map[string]any{
					"type": "string",
				},
			},
			"type": "object",
		},
		ReadOnly: true,
		Handler: func(ctx context.Context, args map[string]any) (any, error) {
			req := &HelloRequest{}
			if err := runtime.DecodeArgs(args, req); err != nil {
				return nil, fmt.Errorf("invalid arguments: %v", err)
			}
			resp, err := client.SayHello(ctx, req)
			if err != nil {
				return nil, err
			}
			return runtime.EncodeProto(resp)
		},
	})
}
