// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: mcp/gateway/v1/annotations.proto

package mcp_gateway_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tool struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ReadOnly      bool                   `protobuf:"varint,4,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	Idempotent    bool                   `protobuf:"varint,5,opt,name=idempotent,proto3" json:"idempotent,omitempty"`
	Destructive   bool                   `protobuf:"varint,6,opt,name=destructive,proto3" json:"destructive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tool) Reset() {
	*x = Tool{}
	mi := &file_mcp_gateway_v1_annotations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tool) ProtoMessage() {}

func (x *Tool) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_gateway_v1_annotations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tool.ProtoReflect.Descriptor instead.
func (*Tool) Descriptor() ([]byte, []int) {
	return file_mcp_gateway_v1_annotations_proto_rawDescGZIP(), []int{0}
}

func (x *Tool) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tool) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Tool) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Tool) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

func (x *Tool) GetIdempotent() bool {
	if x != nil {
		return x.Idempotent
	}
	return false
}

func (x *Tool) GetDestructive() bool {
	if x != nil {
		return x.Destructive
	}
	return false
}

type MethodOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tool          *Tool                  `protobuf:"bytes,1,opt,name=tool,proto3" json:"tool,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MethodOptions) Reset() {
	*x = MethodOptions{}
	mi := &file_mcp_gateway_v1_annotations_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MethodOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodOptions) ProtoMessage() {}

func (x *MethodOptions) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_gateway_v1_annotations_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodOptions.ProtoReflect.Descriptor instead.
func (*MethodOptions) Descriptor() ([]byte, []int) {
	return file_mcp_gateway_v1_annotations_proto_rawDescGZIP(), []int{1}
}

func (x *MethodOptions) GetTool() *Tool {
	if x != nil {
		return x.Tool
	}
	return nil
}

type ServiceOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceOptions) Reset() {
	*x = ServiceOptions{}
	mi := &file_mcp_gateway_v1_annotations_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceOptions) ProtoMessage() {}

func (x *ServiceOptions) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_gateway_v1_annotations_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceOptions.ProtoReflect.Descriptor instead.
func (*ServiceOptions) Descriptor() ([]byte, []int) {
	return file_mcp_gateway_v1_annotations_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceOptions) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceOptions) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var file_mcp_gateway_v1_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*MethodOptions)(nil),
		Field:         51234,
		Name:          "mcp.gateway.v1.mcp",
		Tag:           "bytes,51234,opt,name=mcp",
		Filename:      "mcp/gateway/v1/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*ServiceOptions)(nil),
		Field:         51235,
		Name:          "mcp.gateway.v1.mcp_service",
		Tag:           "bytes,51235,opt,name=mcp_service",
		Filename:      "mcp/gateway/v1/annotations.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional mcp.gateway.v1.MethodOptions mcp = 51234;
	E_Mcp = &file_mcp_gateway_v1_annotations_proto_extTypes[0]
)

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional mcp.gateway.v1.ServiceOptions mcp_service = 51235;
	E_McpService = &file_mcp_gateway_v1_annotations_proto_extTypes[1]
)

var File_mcp_gateway_v1_annotations_proto protoreflect.FileDescriptor

const file_mcp_gateway_v1_annotations_proto_rawDesc = "" +
	"\n" +
	" mcp/gateway/v1/annotations.proto\x12\x0emcp.gateway.v1\x1a google/protobuf/descriptor.proto\"\xb1\x01\n" +
	"\x04Tool\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tread_only\x18\x04 \x01(\bR\breadOnly\x12\x1e\n" +
	"\n" +
	"idempotent\x18\x05 \x01(\bR\n" +
	"idempotent\x12 \n" +
	"\vdestructive\x18\x06 \x01(\bR\vdestructive\"9\n" +
	"\rMethodOptions\x12(\n" +
	"\x04tool\x18\x01 \x01(\v2\x14.mcp.gateway.v1.ToolR\x04tool\">\n" +
	"\x0eServiceOptions\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion:Q\n" +
	"\x03mcp\x12\x1e.google.protobuf.MethodOptions\x18\xa2\x90\x03 \x01(\v2\x1d.mcp.gateway.v1.MethodOptionsR\x03mcp:b\n" +
	"\vmcp_service\x12\x1f.google.protobuf.ServiceOptions\x18\xa3\x90\x03 \x01(\v2\x1e.mcp.gateway.v1.ServiceOptionsR\n" +
	"mcpServiceBLZJgithub.com/linkbreakers-com/grpc-mcp-gateway/mcp/gateway/v1;mcp_gateway_v1b\x06proto3"

var (
	file_mcp_gateway_v1_annotations_proto_rawDescOnce sync.Once
	file_mcp_gateway_v1_annotations_proto_rawDescData []byte
)

func file_mcp_gateway_v1_annotations_proto_rawDescGZIP() []byte {
	file_mcp_gateway_v1_annotations_proto_rawDescOnce.Do(func() {
		file_mcp_gateway_v1_annotations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mcp_gateway_v1_annotations_proto_rawDesc), len(file_mcp_gateway_v1_annotations_proto_rawDesc)))
	})
	return file_mcp_gateway_v1_annotations_proto_rawDescData
}

var file_mcp_gateway_v1_annotations_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_mcp_gateway_v1_annotations_proto_goTypes = []any{
	(*Tool)(nil),                        // 0: mcp.gateway.v1.Tool
	(*MethodOptions)(nil),               // 1: mcp.gateway.v1.MethodOptions
	(*ServiceOptions)(nil),              // 2: mcp.gateway.v1.ServiceOptions
	(*descriptorpb.MethodOptions)(nil),  // 3: google.protobuf.MethodOptions
	(*descriptorpb.ServiceOptions)(nil), // 4: google.protobuf.ServiceOptions
}
var file_mcp_gateway_v1_annotations_proto_depIdxs = []int32{
	0, // 0: mcp.gateway.v1.MethodOptions.tool:type_name -> mcp.gateway.v1.Tool
	3, // 1: mcp.gateway.v1.mcp:extendee -> google.protobuf.MethodOptions
	4, // 2: mcp.gateway.v1.mcp_service:extendee -> google.protobuf.ServiceOptions
	1, // 3: mcp.gateway.v1.mcp:type_name -> mcp.gateway.v1.MethodOptions
	2, // 4: mcp.gateway.v1.mcp_service:type_name -> mcp.gateway.v1.ServiceOptions
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	3, // [3:5] is the sub-list for extension type_name
	1, // [1:3] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_mcp_gateway_v1_annotations_proto_init() }
func file_mcp_gateway_v1_annotations_proto_init() {
	if File_mcp_gateway_v1_annotations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mcp_gateway_v1_annotations_proto_rawDesc), len(file_mcp_gateway_v1_annotations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_mcp_gateway_v1_annotations_proto_goTypes,
		DependencyIndexes: file_mcp_gateway_v1_annotations_proto_depIdxs,
		MessageInfos:      file_mcp_gateway_v1_annotations_proto_msgTypes,
		ExtensionInfos:    file_mcp_gateway_v1_annotations_proto_extTypes,
	}.Build()
	File_mcp_gateway_v1_annotations_proto = out.File
	file_mcp_gateway_v1_annotations_proto_goTypes = nil
	file_mcp_gateway_v1_annotations_proto_depIdxs = nil
}
